import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import { expect,it } from "vitest";
const root=path.resolve(import.meta.dirname,".."); const entries=[
["codex/imouto-dev/.codex-plugin/plugin.json","plugin.json","3da70ffb00e25da0b31b76555dfafda342730359f867a66b78962390ebc04712"],
["codex/imouto-dev/skills/subimouto-dev/SKILL.md","subimouto-dev.md","4048384bd8f4a740472f49975f14c841f16a0bced3fb2f3ee84a455e583db57c"],
["claude/skills/imouto-plan/SKILL.md","imouto-plan.md","dfb13d2b0d9dff2478e35e94a2c67976e279a812d05502971863c9a5bb1f806b"],
["claude/skills/imouto-dispatch/SKILL.md","imouto-dispatch.md","b02c6b7a31fa37346d35951b2fdab47f15efeac245cd3caafecf91334d62b471"]] as const;
it("matches all golden hashes",()=>{for(const [dist,golden,hash] of entries){for(const file of [path.join(root,"dist",dist),path.join(root,"golden",golden)])expect(crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex")).toBe(hash);expect(fs.readFileSync(path.join(root,"dist",dist))).toEqual(fs.readFileSync(path.join(root,"golden",golden)));}});
it("keeps native Codex identifiers out of Yuu's skill",()=>{const text=fs.readFileSync(path.join(root,"dist/dsh/dsh-imouto-dev/presets/yuu/skills/subimouto-dev/SKILL.md"),"utf8");expect(text).not.toContain("Sherry");expect(text).not.toContain("multi_agent_v1__");});
it("keeps Yuu's required fs-search config",()=>{const text=fs.readFileSync(path.join(root,"dist/dsh/dsh-imouto-dev/presets/yuu/agent.cordis.yml"),"utf8");expect(text).toMatch(/- id: tool-fs-search\r?\n  name: '@deepseek-ai\/dsh-tool-fs-search'\r?\n  config:\r?\n    sampleOverCapGlobResults: false/);});
it("keeps every standard agent row in Yuu's preset",()=>{const standard=fs.readFileSync(path.resolve(root,"../deepseek-harness/packages/preset/agent-presets/presets/standard/agent.cordis.yml"),"utf8");const yuu=fs.readFileSync(path.join(root,"dist/dsh/dsh-imouto-dev/presets/yuu/agent.cordis.yml"),"utf8");for(const match of standard.matchAll(/^\s*- id: (.+)$/gm))expect(yuu).toMatch(new RegExp(`^\\s*- id: ${match[1]?.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}$`,"m"));});
